language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.test("JLDArchives"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("JLDArchives")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
